server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: core-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/iatech_core
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Configuration du stockage (utilisée par FileStorageService)
file:
  upload-dir: uploads/

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true


  instance:
    hostname: localhost
    prefer-ip-address: false
    secure-port-enabled: false
    non-secure-port-enabled: true

    status-page-url: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/actuator/health
    home-page-url: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/

    metadata-map:
      zone: zone1
      version: 1.0.0
      profile: dev

    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60




springdoc:
  api-docs:
    path: /v3/api-docs   # was /api/v3/api-docs